"""
BasicPolypharmacyAnalyzer: rule-based multi-drug pattern detection.

Zero learned parameters. Scans pairwise results for three additive
patterns that are especially dangerous when multiple drugs in a
medication list share the same mechanism:

  1. additive_serotonergic (≥2 serotonergic pairs)
  2. additive_qt_prolongation (≥2 QT-prolonging pairs)
  3. additive_cyp_inhibition (≥2 CYP inhibitor pairs)
"""

from dataclasses import dataclass, field

from pharmloop.output import SEVERITY_NAMES

# Severity ordering for ranking
SEVERITY_ORDER = {
    "none": 0,
    "mild": 1,
    "moderate": 2,
    "severe": 3,
    "contraindicated": 4,
    "unknown": -1,
}


@dataclass
class MultiDrugAlert:
    """Alert generated by polypharmacy pattern detection."""
    pattern: str
    alert_text: str
    involved_drugs: list[str]
    involved_pairs: list[tuple[str, str]]
    trigger_mechanism: str
    pair_count: int


@dataclass
class PolypharmacyReport:
    """Result of polypharmacy analysis over a medication list."""
    drugs: list[str]
    total_pairs_checked: int
    highest_severity: str
    pairwise_results: list[tuple[tuple[str, str], object]]
    multi_drug_alerts: list[MultiDrugAlert] = field(default_factory=list)
    skipped_drugs: list[str] = field(default_factory=list)


class BasicPolypharmacyAnalyzer:
    """
    Phase 4a polypharmacy: pairwise scan + three additive patterns.

    Zero learned parameters. Rule-based detection of the three most
    dangerous multi-drug patterns.
    """

    ADDITIVE_PATTERNS = {
        "additive_serotonergic": {
            "trigger_mechanism": "serotonergic",
            "min_count": 2,
            "alert": (
                "Multiple serotonergic agents detected in this medication list. "
                "Risk of serotonin syndrome is significantly elevated with "
                "multiple serotonergic drugs. Consider reducing serotonergic "
                "burden or increasing monitoring frequency."
            ),
            "severity_bump": True,
        },
        "additive_qt_prolongation": {
            "trigger_mechanism": "qt_prolongation",
            "min_count": 2,
            "alert": (
                "Multiple QT-prolonging agents detected. Combined QT "
                "prolongation risk exceeds the sum of individual risks. "
                "Obtain baseline ECG and monitor QTc interval closely. "
                "Consider alternatives where possible."
            ),
            "severity_bump": True,
        },
        "additive_cyp_inhibition": {
            "trigger_mechanism": "cyp_inhibition",
            "min_count": 2,
            "alert": (
                "Multiple CYP inhibitors detected. Combined enzyme inhibition "
                "may significantly increase substrate drug levels beyond what "
                "any single inhibitor would cause. Monitor drug levels for "
                "all CYP substrates in this medication list."
            ),
            "severity_bump": True,
        },
    }

    def analyze(
        self,
        drug_names: list[str],
        pairwise_results: dict[tuple[str, str], object],
        skipped_drugs: list[str] | None = None,
    ) -> PolypharmacyReport:
        """
        Analyze pairwise results for the three additive patterns.

        Args:
            drug_names: List of all drug names in the medication list.
            pairwise_results: Dict mapping (drug_a, drug_b) → InteractionResult.
            skipped_drugs: Drug names that were not in the registry and whose
                pairs were skipped entirely. Surfaced in the report so callers
                know the analysis is incomplete.

        Returns:
            PolypharmacyReport with ranked pairs and any multi-drug alerts.
        """
        # Count mechanism occurrences across all pairs
        mechanism_counts: dict[str, int] = {}
        mechanism_pairs: dict[str, list[tuple[str, str]]] = {}
        for pair, result in pairwise_results.items():
            for mech in result.mechanisms:
                mechanism_counts[mech] = mechanism_counts.get(mech, 0) + 1
                mechanism_pairs.setdefault(mech, []).append(pair)

        # Check additive patterns
        alerts = []
        for pattern_name, pattern in self.ADDITIVE_PATTERNS.items():
            trigger_mech = pattern["trigger_mechanism"]
            count = mechanism_counts.get(trigger_mech, 0)
            if count >= pattern["min_count"]:
                involved_pairs = mechanism_pairs.get(trigger_mech, [])
                involved_drugs = set()
                for a, b in involved_pairs:
                    involved_drugs.add(a)
                    involved_drugs.add(b)

                alerts.append(MultiDrugAlert(
                    pattern=pattern_name,
                    alert_text=pattern["alert"],
                    involved_drugs=sorted(involved_drugs),
                    involved_pairs=involved_pairs,
                    trigger_mechanism=trigger_mech,
                    pair_count=count,
                ))

        # Rank pairwise results by severity × confidence
        ranked_pairs = sorted(
            pairwise_results.items(),
            key=lambda x: (
                SEVERITY_ORDER.get(x[1].severity, 0),
                x[1].confidence,
            ),
            reverse=True,
        )

        highest = ranked_pairs[0][1].severity if ranked_pairs else "none"

        return PolypharmacyReport(
            drugs=drug_names,
            total_pairs_checked=len(pairwise_results),
            highest_severity=highest,
            pairwise_results=ranked_pairs,
            multi_drug_alerts=alerts,
            skipped_drugs=skipped_drugs or [],
        )
